# Generated by Django 3.0.4 on 2020-05-31 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200421_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(error_messages={'unique': 'A user with that email address already exists.'}, help_text='электронная почта', max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator('[A-Za-z@-\\.]{1,32}')], verbose_name='Email'),
        ),
    ]
