# Generated by Django 3.0.3 on 2020-02-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_number', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('pressure_before', models.FloatField()),
                ('pressure_after', models.FloatField()),
                ('temperature_before', models.FloatField()),
                ('consumption_before', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Initial data',
                'unique_together': {('well_number', 'timestamp')},
            },
        ),
    ]
