# Generated by Django 3.0.3 on 2020-02-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InitialData',
            new_name='SensorsData',
        ),
        migrations.AlterModelOptions(
            name='sensorsdata',
            options={'verbose_name_plural': 'Sensors data'},
        ),
    ]
