# Generated by Django 3.0.3 on 2020-02-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0002_auto_20200218_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorsdata',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
