# Generated by Django 3.0.3 on 2020-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0003_sensorsdata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorsdata',
            name='file',
            field=models.FilePathField(null=True),
        ),
    ]
