# Generated by Django 3.0.3 on 2020-02-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0005_auto_20200218_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorsdata',
            name='file',
        ),
    ]
