# Generated by Django 3.0.3 on 2020-02-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0006_remove_sensorsdata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorsdata',
            name='consumption_before',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='pressure_after',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='pressure_before',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='temperature_before',
            field=models.FloatField(blank=True),
        ),
    ]
