# Generated by Django 3.0.3 on 2020-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0007_auto_20200220_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorsdata',
            name='consumption_before',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='pressure_after',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='pressure_before',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='temperature_before',
            field=models.FloatField(null=True),
        ),
    ]
